# Weight Initialization

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.datasets import mnist
from keras.initializers import glorot_uniform, he_uniform
from sklearn.model_selection import train_test_split

2025-08-04 06:12:08.016555: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1754287928.272856      36 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1754287928.349530      36 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
# Load the MNIST dataset
(X_train_full, y_train_full), (X_test, y_test) = mnist.load_data()
print(X_train_full)
print(y_train_full)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0 4 ... 5 6 8]


Dividing the input data by 255 is a normalization step commonly applied to image data before feeding it into neural networks.

In the MNIST dataset, pixel values range from 0 to 255, where 0 represents black and 255 represents white. By dividing each pixel value by 255, you scale the values to be between 0 and 1. 

In [3]:
# Normalize the input data
X_train_full = X_train_full.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0


The step X_train_full.reshape((-1, 28*28)) is used to reshape the input images from a 2D array (representing images) into a 1D array (vector).

In [4]:
# Flatten the input images
X_train_full = X_train_full.reshape((-1, 28*28))
X_test = X_test.reshape((-1, 28*28))
print(X_train_full)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# Split the full training set into training and validation sets
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)

In [6]:
# Define the model with Xavier Glorot initialization and tanh activation
model_xavier = Sequential([
    Dense(512, activation='tanh', kernel_initializer=glorot_uniform(), input_shape=(28*28,)),
    Dense(512, activation='tanh', kernel_initializer=glorot_uniform()),
    Dense(10, activation='softmax')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-08-04 06:15:17.998296: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [7]:
# Compile the model
model_xavier.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [8]:
# Train the model
history_xavier = model_xavier.fit(X_train, y_train, epochs=10, batch_size=128, validation_data=(X_valid, y_valid))

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 8s 16ms/step - accuracy: 0.8662 - loss: 0.4375 - val_accuracy: 0.9495 - val_loss: 0.1773
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9526 - loss: 0.1554 - val_accuracy: 0.9656 - val_loss: 0.1137
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9710 - loss: 0.0984 - val_accuracy: 0.9698 - val_loss: 0.0996
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9809 - loss: 0.0624 - val_accuracy: 0.9753 - val_loss: 0.0859
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9852 - loss: 0.0490 - val_accuracy: 0.9690 - val_loss: 0.0988
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9886 - loss: 0.0381 - val_accuracy: 0.9768 - val_loss: 0.0775
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9942 - loss: 0.0211 - val_accuracy: 0.9764 - val_loss: 0.0773
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9953 - loss: 0.0174 - val_accu

In [9]:
# Define the model with He initialization and ReLU activation
model_he = Sequential([
    Dense(512, activation='relu', kernel_initializer=he_uniform(), input_shape=(28*28,)),
    Dense(512, activation='relu', kernel_initializer=he_uniform()),
    Dense(10, activation='softmax')
])

In [10]:
# Compile the model
model_he.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [11]:
# Train the model
history_he = model_he.fit(X_train, y_train, epochs=10, batch_size=128, validation_data=(X_valid, y_valid))

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - accuracy: 0.8708 - loss: 0.4326 - val_accuracy: 0.9643 - val_loss: 0.1192
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.9733 - loss: 0.0895 - val_accuracy: 0.9710 - val_loss: 0.0881
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9840 - loss: 0.0545 - val_accuracy: 0.9775 - val_loss: 0.0752
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9889 - loss: 0.0356 - val_accuracy: 0.9720 - val_loss: 0.0964
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9929 - loss: 0.0246 - val_accuracy: 0.9776 - val_loss: 0.0854
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.9931 - loss: 0.0194 - val_accuracy: 0.9779 - val_loss: 0.0871
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9958 - loss: 0.0133 - val_accuracy: 0.9761 - val_loss: 0.0934
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9947 - loss: 0.0157 - val_accu

In [12]:
# Print the final training and validation accuracies
print("Xavier Glorot Initialization:")
print("Training Accuracy:", history_xavier.history['accuracy'][-1])
print("Validation Accuracy:", history_xavier.history['val_accuracy'][-1])
print("\nHe Initialization:")
print("Training Accuracy:", history_he.history['accuracy'][-1])
print("Validation Accuracy:", history_he.history['val_accuracy'][-1])

Xavier Glorot Initialization:
Training Accuracy: 0.9962916374206543
Validation Accuracy: 0.9792500138282776

He Initialization:
Training Accuracy: 0.9953333139419556
Validation Accuracy: 0.9769166707992554
