# tensor flow

In [1]:
#for installing tensorflow
!pip install tensorflow

In [3]:
# version check
import tensorflow as tf
print("Tensorflow version :",tf.__version__)

2025-08-06 11:42:52.304719: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1754480572.549670      36 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1754480572.624532      36 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


Tensorflow version : 2.18.0


# tensor constant

In [8]:

iscale=tf.constant(42)

In [9]:
iscale

<tf.Tensor: shape=(), dtype=int32, numpy=42>

TensorFlow library mein NumPy library ka use hota hai. NumPy, short for Numerical Python, ek popular numerical computing library hai jo Python mein array operations aur mathematical functions provide karta hai. TensorFlow, jo ki deep learning ke liye use hota hai, internally NumPy arrays ko manipulate karta hai, isliye TensorFlow use karte waqt, NumPy ka familiarity helpful hota hai. TensorFlow ki kuch functions aur operations NumPy arrays ko as input accept karte hain, aur kuch TensorFlow tensors ko NumPy arrays mein convert karne ke liye functions available hote hain. Isliye, deep learning ke projects mein NumPy aur TensorFlow ko saath mein use kiya ja sakta hai.

In [11]:
iscale.numpy()

42

In [13]:
iscale=tf.constant(1,dtype=tf.int32)

In [14]:
iscale

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
iscale.numpy()

1

In [16]:
iscale=tf.constant([[9,8],[7,6]])
iscale

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 8],
       [7, 6]], dtype=int32)>

In [17]:
iscale.numpy()

array([[9, 8],
       [7, 6]], dtype=int32)

In [18]:
print("shape:",iscale.shape)
print(iscale.dtype)

shape: (2, 2)
<dtype: 'int32'>


# Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [19]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [20]:
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [21]:
import tensorflow as tf
const1=tf.constant([[1,2,3],[4,5,6]])
const2=tf.constant([[7,8,9],[4,6,5]])
result=tf.add(const1,const2)

In [22]:
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [ 8, 11, 11]], dtype=int32)>

# # We have defined two constants and we add one value to the other. As a result, we got a Tensor object with the result of the adding.

# Random Constant

In [23]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.44914424,  0.58400756],
       [-0.26742607,  0.47672558]], dtype=float32)>

In [24]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 8],
       [2, 0]], dtype=int32)>

# Variable

# A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

# Declaring Variable

In [25]:
var0=24
var1=tf.Variable(42)
var2=tf.Variable([1,2,3],[1,8,9],[4,6,9])
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

# TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

# The datatype can be explicitly specified

In [27]:
float=tf.Variable(89,dtype=tf.float64)
float.dtype

tf.float64

TensorFlow has a large number of built-in datatypes.

In [ ]:

datatype	description
tf.float16	16-bit half-precision floating-point.
tf.float32	32-bit single-precision floating-point.
tf.float64	64-bit double-precision floating-point.
tf.bfloat16	16-bit truncated floating-point.
tf.complex64	64-bit single-precision complex.
tf.complex128	128-bit double-precision complex.
tf.int8	8-bit signed integer.
tf.uint8	8-bit unsigned integer.
tf.uint16	16-bit unsigned integer.
tf.uint32	32-bit unsigned integer.
tf.uint64	64-bit unsigned integer.
tf.int16	16-bit signed integer.
tf.int32	32-bit signed integer.
tf.int64	64-bit signed integer.
tf.bool	Boolean.
tf.string	String.
tf.qint8	Quantized 8-bit signed integer.
tf.quint8	Quantized 8-bit unsigned integer.
tf.qint16	Quantized 16-bit signed integer.
tf.quint16	Quantized 16-bit unsigned integer.
tf.qint32	Quantized 32-bit signed integer.
tf.resource	Handle to a mutable resource.
tf.variant	Values of arbitrary types.
    

 # To reassign a variable, use var.assign()

In [31]:
var=tf.Variable(89)
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=89>

In [32]:
var.assign(98)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=98>

In [34]:
initial_value=tf.random.normal(shape=(2,3))
a=tf.Variable(initial_value)
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.7224259 ,  0.91172653,  0.6782744 ],
       [-1.3435555 , -0.5182258 ,  0.8265326 ]], dtype=float32)>

We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [ ]:
tf: This stands for TensorFlow, the deep learning framework.
random: Indicates that this function generates random numbers.
normal: Specifies that the random numbers will be drawn from a normal distribution.

# Shaping a tensor

In [37]:
tensor=tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.

In [38]:
tensor1=tf.reshape(tensor,shape=(2,6))
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [39]:
tensor2=tf.reshape(tensor,shape=(1,12))
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

 # Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [40]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [41]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

(the shape is () because the output here is a scalar value)

 # Specifying an element of a tensor

In [42]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [43]:
tensor3=tensor[1,0,2]
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

 # Casting a tensor to a NumPy/Python variable

In [44]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [46]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


# Finding the size (number of elements) of a tensor

In [47]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [49]:
tensor_size=tf.size(input=tensor).numpy()
tensor_size

12

In [50]:
#the datatype of a tensor
tensor3.dtype

tf.float32

 # Tensorflow mathematical operations
Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.

In [51]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d=tf.square(c)
e=tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.31279668  0.10677262]
 [-1.0875039   0.19674774]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.3611238   0.45033658]
 [ 1.2354892  -1.2458156 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.6739205   0.5571092 ]
 [ 0.14798534 -1.0490679 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.45416886 0.31037062]
 [0.02189966 1.1005434 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.5097063 1.7456189]
 [1.159496  0.3502641]], shape=(2, 2), dtype=float32)


# # Performing element-wise primitive tensor operations

In [52]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [53]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

# Broadcasting
Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

The simplest example is that of multiplying a tensor by a scalar:

In [54]:
tensor4=tensor*4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


# Transpose Matrix multiplication

In [55]:
matrix_u=tf.constant([[1,2,3]])
matrix_v=tf.constant([[4,5,6]])
tf.matmul(matrix_u,tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

In [ ]:
Result=(1*4)+(2*5)+(3*6)=4+7+9=20

# Casting a tensor to another (tensor) datatype

In [56]:
print(tensor)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [57]:
print(tensor.dtype)

<dtype: 'float32'>


In [58]:
i=tf.cast(tensor1,dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)>

# With truncation

In [60]:
j=tf.cast(tf.constant(4.142456655),dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

# Declaring Ragged tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.

 # The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [61]:
ragged=tf.ragged.constant([[5,2,6,1],[],[1,5,8,9],[1,5,3],[7],[9,0]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])
print(ragged[5,:])


<tf.RaggedTensor [[5, 2, 6, 1], [], [1, 5, 8, 9], [1, 5, 3], [7], [9, 0]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([1 5 8 9], shape=(4,), dtype=int32)
tf.Tensor([1 5 3], shape=(3,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int32)
tf.Tensor([9 0], shape=(2,), dtype=int32)


# Finding the squared difference between two tensors

In [63]:
varx=[1,2,3,4,5]
vary=5
varz=tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4,  1,  0], dtype=int32)>

The Python variables, varx and vary, are cast into tensors and that vary is then broadcast across varx in this example. So, for example, the first calculation is (1-5)2 = 16.

# Finding the mean

The following is the signature of tf.reduce_mean().

Note that this is equivalent to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type (defaulting to float64):

tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)

In [65]:
# defining a constant
numbers=tf.constant([[4,5],[6,7]])

# Find the mean across all axes (use the default axis = None)

In [67]:
tf.reduce_mean(input_tensor=numbers)
#( 4. + 5. + 7. + 3.)/4 = 4.75

<tf.Tensor: shape=(), dtype=int32, numpy=5>

# Find the mean across columns (that is, reduce rows) with this

In [69]:
tf.reduce_mean(input_tensor=numbers,axis=0)
# [ (4. + 7. )/2 , (5. + 3.)/2 ] = [5.5, 4.]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

# When keepdims is True, the reduced axis is retained with a length of 1:

In [71]:
tf.reduce_mean(input_tensor=numbers,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 6]], dtype=int32)>

# Find the mean across rows (that is, reduce columns) with this:

In [72]:
tf.reduce_mean(input_tensor=numbers,axis=1)
# [ (4. + 5. )/2 , (7. + 3. )/2] = [4.5, 5]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

# When keepdims is True, the reduced axis is retained with a length of 1:

In [73]:
tf.reduce_mean(input_tensor=numbers,axis=1,keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[4],
       [6]], dtype=int32)>

# Generating tensors filled with random values

# Using tf.random.normal()
tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

The required signature is as follows:

tf. random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

In [77]:
tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None,name=None)
ran=tf.random.normal(shape=(3,2),mean=10.0,stddev=2)
print(ran)

tf.Tensor(
[[11.858692 10.516267]
 [ 6.881455 12.093032]
 [ 9.411278  9.091659]], shape=(3, 2), dtype=float32)


# Using tf.random.uniform()

The required signature is this:

tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't. Take this, for example:

In [78]:
tf.random.uniform(shape=(2,4),minval=0,maxval=None,dtype=tf.float32,seed=None,name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.01983392, 0.29778945, 0.4067055 , 0.5387151 ],
       [0.3433602 , 0.765748  , 0.6364212 , 0.05463743]], dtype=float32)>

# Setting the seed

In [79]:
tf.random.set_seed(11)
ran1=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
ran2=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
print(ran1)#Call1
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [80]:
tf.random.set_seed(11) #same seed
ran1=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
ran2=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
print(ran1)#Call1
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [81]:
tf.random.set_seed(12)
ran1=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
ran2=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
print(ran1)#Call1
print(ran2)

tf.Tensor(
[[2 2]
 [6 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 2]
 [2 2]], shape=(2, 2), dtype=int32)


In [82]:
tf.random.set_seed(11)
ran1=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
ran2=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
print(ran1)#Call1
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


# Practical example of Random values using Dices

In [83]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
print("the dice 1 is")
print(dice1)
print("the dice 2 is")
print(dice2)
# We may add dice1 and dice2 since they share the same shape and size.
dice_sum = dice1 + dice2
print("the dice sum is")
print(dice_sum)
# We've got three separate 10x1 matrices. To produce a single
# 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
print(resulting_matrix)

the dice 1 is
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[5],
       [4],
       [5],
       [3],
       [1],
       [4],
       [5],
       [6],
       [3],
       [2]], dtype=int32)>
the dice 2 is
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[5],
       [3],
       [3],
       [3],
       [4],
       [1],
       [1],
       [4],
       [3],
       [3]], dtype=int32)>
the dice sum is
tf.Tensor(
[[10]
 [ 7]
 [ 8]
 [ 6]
 [ 5]
 [ 5]
 [ 6]
 [10]
 [ 6]
 [ 5]], shape=(10, 1), dtype=int32)
tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


# Finding the indices of the largest and smallest element

In [ ]:
The signatures of the functions are as follows:

tf.argmax(input, axis=None, name=None, output_type=tf.int64 )

tf.argmin(input, axis=None, name=None, output_type=tf.int64 )

In [84]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)


i = tf.argmax(input=t5)
print('index of max; ', i)
print('Max element: ',t5[i].numpy())


i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy())


t6 = tf.reshape(t5, [3,3])
print(t6)


i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i)

i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i)
print(t6)

i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i)

i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i)


tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max across cols:  [1 0 2]
indices of min across cols:  [0 1 1]


# Saving and restoring tensor values using a checkpoint

In [85]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


# Using tf.function
tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.

In [86]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == f2(x,y).numpy()
#The assert passes, so there is no output

# Calculate the gradient

# GradientTape
Another difference from numpy is that it can automatically track the gradient of any variable.

Open one GradientTape and tape.watch() track variables through

In [87]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


For all variables, the calculation is tracked by default and used to find the gradient, so do not usetape.watch()

In [88]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)



You can GradientTapefind higher-order derivatives by opening a few more:

In [89]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.4264985  0.6867533 ]
 [0.44663432 0.5015956 ]], shape=(2, 2), dtype=float32)
