# Iterating Numpy array
# 1D

In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)
print()
for i in arr1:
    print(i)

[1 2 3 4 5]
1

1
2
3
4
5


# 2D array

In [20]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print()
for i in arr1:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]]
2

1
2
3
4
5
6


# 3D array

In [29]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr1.ndim)
print()
for i in arr1:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


# nditer function

In [38]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr1.ndim)
print()
for i in np.nditer(arr1):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


In [40]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr1.ndim)
print()
for i in np.nditer(arr1,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


# ndenumerate

In [49]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr1.ndim)
for i in np.ndenumerate(arr1):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((0, 2, 0), 7)
((0, 2, 1), 8)
((0, 2, 2), 9)


In [55]:
import numpy as np
arr1=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(arr1)
print(arr1.ndim)
print()
for i in np.ndenumerate(arr1):
    print(i)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
4

((0, 0, 0, 0), 1)
((0, 0, 0, 1), 2)
((0, 0, 0, 2), 3)
((0, 0, 1, 0), 4)
((0, 0, 1, 1), 5)
((0, 0, 1, 2), 6)
((0, 0, 2, 0), 7)
((0, 0, 2, 1), 8)
((0, 0, 2, 2), 9)
((0, 0, 3, 0), 10)
((0, 0, 3, 1), 11)
((0, 0, 3, 2), 12)


# copy vs view function

In [66]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print()
v=arr1.view()
print(v)

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [70]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1[3]=56
print(arr1)
print()
v=arr1.view()
print(v)

[ 1  2  3 56  5  6]

[ 1  2  3 56  5  6]


In [72]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
c=arr1.copy()
print(arr1)
print(c)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [88]:
import numpy as np
arr2=np.array([1,2,3,4,5,6])
arr2[3]=96
print(arr2)
print()
c=arr2.copy()
print(c)

[ 1  2  3 96  5  6]

[ 1  2  3 96  5  6]


# join array
 # concatenate

In [95]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1)
print(arr2)
print()
c=np.concatenate((arr1,arr2))
print(c)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [107]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1)
print()
print(arr2)
print()
con=np.concatenate((arr1,arr2),axis=1)
print(con)


[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [109]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1)
print()
print(arr2)
print()
con=np.concatenate((arr1,arr2),axis=0)
print(con)


[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# vstack,hstack,dstack

In [124]:
import numpy as np
x=np.array([1,2,3])
y=np.array([7,8,9])
z=np.array([13,14,15])
print(x)
print()
print(y)
print() 
print(z)
print()

a=np.vstack((x,y,z))
print(a)
print()

b=np.hstack((x,y,z))
print(b)
print()

c=np.dstack((x,y,z))
print(c)

[1 2 3]

[7 8 9]

[13 14 15]

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

[ 1  2  3  7  8  9 13 14 15]

[[[ 1  7 13]
  [ 2  8 14]
  [ 3  9 15]]]
