# data types in numPy

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [6]:
import numpy as np
arr1=np.array([1.2,1.3,1.4,1.5,1.6])
print(arr1.dtype)

float64


In [8]:
import numpy as np
arr2=np.array(["code","ai","belgium","data","science"])
print(arr2.dtype)

<U7


In [12]:
import numpy as np
arr3=np.array(["code","ai","data","center","tiger",1,2,3,4])
print(arr3.dtype)

<U11


# converting data type into another type

In [17]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1=np.array([1,2,3,4,5],dtype=np.int16)
print(x1)
print(x1.dtype)


[1 2 3 4 5]
int32
[1 2 3 4 5]
int16


In [29]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a.dtype)

a1=np.array([1,2,3,4,5],dtype=np.float32)
print(a1)
print(a1.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [35]:
import numpy as np
m=np.array([1,2,3,4,5])
print(m)
print(m.dtype)
m1=np.float64(m)
print(m1)
print(m1.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64


In [43]:
import numpy as np
m=np.array([1,2,3,4,5])
print(m)
print(m.dtype)
m1=np.float64(m)
print(m1)
print(m1.dtype)
m2=np.int64(m1)
print(m2)
print(m2.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64
[1 2 3 4 5]
int64


In [45]:
import numpy as np
x=np.array([1,2,3,4,5])
y=x.astype(complex)
print(x)
print(x.dtype)
print(y)
print(y.dtype)

[1 2 3 4 5]
int32
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
complex128


# arithmetic addition in numpy

addition

In [51]:
import numpy as np
x=np.array([1,2,3,4])
y=x+3
print(y)

[4 5 6 7]


In [53]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=x+y
print(z)

[ 6  8 10 12]


In [55]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.add(x,y)
print(z)

[ 6  8 10 12]


In [61]:
import numpy as np
x=np.array([1,2,3,4])
y=x-3
print(y)


[-2 -1  0  1]


In [67]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([6,5,8,9])
z=np.subtract(x,y)
print(z)

[-5 -3 -5 -5]


In [69]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([6,5,8,9])
z=x-y
print(z)

[-5 -3 -5 -5]


In [71]:
import numpy as np
x=np.array([1,2,3,4])
y=x*3
print(y)

[ 3  6  9 12]


In [73]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([4,5,6,7])
z=x*y
print(z)

[ 4 10 18 28]


In [79]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.multiply(x,y)
print(z)

[ 5 12 21 32]


In [81]:
import numpy as np
x=np.array([1,2,3,4])
y=x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333]


In [83]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.divide(x,y)
print(z)

[0.2        0.33333333 0.42857143 0.5       ]


In [85]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([4,5,6,7])
z=x/y
print(z)

[0.25       0.4        0.5        0.57142857]


# modulus

In [88]:
import numpy as np
x=np.array([1,2,3,4])
y=x%3
print(y)

[1 2 0 1]


In [90]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=x%y
print(z)

[1 2 3 4]


In [92]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.mod(x,y)
print(z)

[1 2 3 4]


# reciprocal

In [95]:
import numpy as np
x=np.array([1,2,3,4])
y=np.reciprocal(x)
print(y)

[1 0 0 0]
