# arithmetic operators in 2D

In [2]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1+arr2)


[[ 8 10 12]
 [14 16 18]]


In [4]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1-arr2)

[[-6 -6 -6]
 [-6 -6 -6]]


In [8]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1*arr2)

[[ 7 16 27]
 [40 55 72]]


In [10]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,11]])
print(arr1/arr2)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.54545455]]


# arithmetic operations in 3D

In [13]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
print(arr1+arr2)

[[[11 13 15]
  [17 19 21]
  [23 25 27]]]


In [17]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]]])
arr2=np.array([[[10,11,12],[13,14,15]]])
print(arr1-arr2)

[[[-9 -9 -9]
  [-9 -9 -9]]]


In [21]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]]])
arr2=np.array([[[7,8,9],[10,12,13]]])
print(arr1*arr2)

[[[ 7 16 27]
  [40 60 78]]]


In [25]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]]])
arr2=np.array([[[7,8,9],[10,11,12]]])
print(arr1/arr2)

[[[0.14285714 0.25       0.33333333]
  [0.4        0.45454545 0.5       ]]]


# arithmetic functions
# max and min alongwith index

In [30]:
import numpy as np
ar1=np.array([1,25,12,88,63,44,13,100])
print(np.max(ar1))
print(np.min(ar1))

100
1


In [38]:
import numpy as np
ar1=np.array([1,25,12,88,63,44,13,100])
print(np.max(ar1),np.argmax(ar1))
print(np.min(ar1),np.argmin(ar1))

100 7
1 0


In [54]:
import numpy as np
arr1=np.array([[1,2,3],[10,20,30]])
print(arr1)
print(arr1.ndim)
print(np.max(arr1,axis=0))


[[ 1  2  3]
 [10 20 30]]
2
[10 20 30]


In [60]:
import numpy as np
arr1=np.array([[1,2,3],[10,20,50]])
print(arr1)
print(arr1.ndim)
print(np.min(arr1,axis=1))

[[ 1  2  3]
 [10 20 50]]
2
[ 1 10]


In [62]:
import numpy as np
arr1=np.array([[1,2,3],[10,20,50]])
print(arr1)
print(arr1.ndim)
print(np.max(arr1,axis=1))

[[ 1  2  3]
 [10 20 50]]
2
[ 3 50]


In [64]:
import numpy as np
arr1=np.array([[1,2,3],[10,20,30]])
print(arr1)
print(arr1.ndim)
print(np.min(arr1,axis=0))

[[ 1  2  3]
 [10 20 30]]
2
[1 2 3]


In [66]:
import numpy as np
arr1=np.array([[1,2,3],[10,20,50]])
print(arr1)
print(arr1.ndim)
print(np.max(arr1,axis=0))

[[ 1  2  3]
 [10 20 50]]
2
[10 20 50]


# square root

In [71]:
import numpy as np
arr1=np.array([4,16,9,81])
print(np.sqrt(arr1))

[2. 4. 3. 9.]


In [75]:
import numpy as np
arr1=np.array([[4,16],[9,81]])
print(np.sqrt(arr1))

[[2. 4.]
 [3. 9.]]


# sin value and cos value

In [78]:
import numpy as np
arr1=np.array([1,2,3])
print(np.sin(arr1))

[0.84147098 0.90929743 0.14112001]


In [80]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(np.sin([arr1]))

[[[ 0.84147098  0.90929743  0.14112001]
  [-0.7568025  -0.95892427 -0.2794155 ]]]


In [82]:
import numpy as np
arr1=np.array([1,2,3])
print(np.cos([arr1]))

[[ 0.54030231 -0.41614684 -0.9899925 ]]


In [86]:
import numpy as np
arr1=np.array([[4,5,6],[7,8,9]])
print(np.cos(arr1))

[[-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


# cumsum

In [89]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(np.cumsum(arr1))

[ 1  3  6 10 15 21]


In [91]:
import numpy as np
arr1=np.array([12,55,100,8,9,6,33,25])
print(np.cumsum(arr1))

[ 12  67 167 175 184 190 223 248]


In [93]:
import numpy as np
arr1=np.array([[12,13,14,15],[88,96,200,300]])
print(np.cumsum(arr1))

[ 12  25  39  54 142 238 438 738]


# broadcasting numpy in array

In [100]:
arr1=np.array([1,2,3])
arr2=np.array([4,5])
print(arr1.shape)
print(arr2.shape)
arr3=arr1+arr2
print(arr3)


(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [124]:
import numpy as np
arr1=np.array([[1,2,3,4]])
print(arr1.shape)
print(arr1)
print(arr1.ndim)
print()

arr2=np.array([[1],[2],[3],[4]])
print(arr2.shape)
print(arr2.ndim)
arr3=arr1+arr2
print(arr3)

(1, 4)
[[1 2 3 4]]
2

(4, 1)
2
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [150]:
import numpy as np
arr1=np.array([[1],[4]])
print(arr1.shape)
print(arr1)
print(arr1.ndim)
print()

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
print(arr2)
print(arr2.ndim)
print()

print(arr1+arr2)
print()
print(arr1-arr2)
print()
print(arr1*arr2)
print()
print(arr1/arr2)

(2, 1)
[[1]
 [4]]
2

(2, 3)
[[1 2 3]
 [4 5 6]]
2

[[ 2  3  4]
 [ 8  9 10]]

[[ 0 -1 -2]
 [ 0 -1 -2]]

[[ 1  2  3]
 [16 20 24]]

[[1.         0.5        0.33333333]
 [1.         0.8        0.66666667]]
