# numpy in array
# indexing in numpy array(1D)

In [5]:
import numpy as np
arr1=np.array([10,12,13,14,15,45])
print(arr1[4])

15


In [9]:
import numpy as np
arr1=np.array([10,12,14,15,45,54])
print(arr1[5])

54


In [11]:
import numpy as np
arr1=np.array([10,11,12,13,14,45])
print(arr1[-1])

45


# 2d array(indexing)

In [14]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
print(arr1[1,0])

3


In [16]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[1,1])

5


In [18]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[2,0])

7


In [20]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0,0])

1


# 3d array(indexing)

In [27]:
import numpy as np
arr1=np.array([[[1,2],[3,4],[5,6]]])
print(arr1)
print(arr1.ndim)
print(arr1[0,1,1])

[[[1 2]
  [3 4]
  [5 6]]]
3
4


In [33]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr1.ndim)
print(arr1[0,1,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
6


# 5d array(indexing)

In [42]:
import numpy as np
arr1=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(arr1)
print(arr1.ndim)
print(arr1[0,0,0,2,1])

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5
8


# slicing in numpy array(1D)

In [45]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[2:8])

[3 4 5 6 7 8]


In [47]:
import numpy as np
arr1=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr1[2:8:2])

[30 50 70]


In [49]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[0:5])

[1 2 3 4 5]


In [51]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[:])

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [55]:
import numpy as np
arr1=np.array([1,2,5,8,6,9,10,50,30])
print(arr1[3:5])

[8 6]


# slicing numpy in 2D array

In [65]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(arr1)
print(arr1[1,1:5])

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
[11 12 13 14]


In [67]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr1)
print(arr1[0,0:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 2 3 4]


In [69]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[0,0:4:2])

[1 3]


In [71]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[0,::-1])

[5 4 3 2 1]


In [79]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[1,::-1])

[10  9  8  7  6]


# slicing 3D numpy array

In [90]:
import numpy as np
arr1=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1[0,1,0:4])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]

3

[6 7 8 9]


In [92]:
import numpy as np
arr1=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1[0,1,::-1])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]

3

[10  9  8  7  6]


In [94]:
import numpy as np
arr1=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1[0,0,::-1])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]

3

[5 4 3 2 1]
