# NumPy

In [4]:
import numpy
import numpy as np

x=np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
l=[1,2,3,4,5]
print(l)
print(type(l))

[1, 2, 3, 4, 5]
<class 'list'>


# array is faster than list

In [13]:
%timeit [i**5 for i in range(1,10)]

2.43 μs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
import numpy as np
%timeit np.arange(1,10)

1.78 μs ± 315 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# creating numpy arrays

In [22]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [28]:
import numpy as np
x=np.array([[1,2,3,4,5]])
print(x)
print(type(x))
print(x.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [34]:
import numpy as np
x=np.array([[[12,23,55,96]]])
print(x)
print(type(x))
print(x.ndim)

[[[12 23 55 96]]]
<class 'numpy.ndarray'>
3


In [36]:
import numpy as np
m=[]
for i in range(1,5):
    num=input("enter a number")
    m.append(num)

print(np.array(m))

enter a number 1
enter a number 2
enter a number 3
enter a number 4


['1' '2' '3' '4']


In [38]:
import numpy as np
m=[]
for i in range(1,5):
    num=input("enter a number")
    m.append(num)

y=np.array(m)
print(y)
print(type(y))

enter a number 1
enter a number 2
enter a number 3
enter a number 4


['1' '2' '3' '4']
<class 'numpy.ndarray'>


# creating 2d array

In [45]:
import numpy as np
arr2=np.array([[1,2,3,4],[4,5,6,7],[10,12,13,14]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 12 13 14]]
2


In [49]:
import numpy as np
arr2=np.array([[1,2,3,4,5,6,7],[10,20,30,40,50,60,70],[100,200,300,400,500,600,700]])
print(arr2)
print(arr2.ndim)

[[  1   2   3   4   5   6   7]
 [ 10  20  30  40  50  60  70]
 [100 200 300 400 500 600 700]]
2


# creating 3d array

In [52]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


# creating multidimensional array

In [57]:
arrn=np.array([1,2,3,4],ndmin=15)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]
15


In [63]:
arr3=np.array(([1,2,3,4],[5,6,7,8]),ndmin=25)
print(arr3)
print(arr3.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]
                        [5 6 7 8]]]]]]]]]]]]]]]]]]]]]]]]]
25
