# NumPy array with all its elements values as zero

In [3]:
import numpy as np
arr=np.zeros(5)
print(arr)
print(arr.ndim)

[0. 0. 0. 0. 0.]
1


In [26]:
import numpy as np
arr2=np.zeros((4,3))
print(arr2)
print(arr2.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [24]:
import numpy as np
arr3=np.zeros((2,4,3))
print(arr3)
print(arr3.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3


# Numpy array with all elements value as 1

In [16]:
import numpy as np
arr=np.ones(6)
print(arr)
print(arr.ndim)

[1. 1. 1. 1. 1. 1.]
1


In [20]:
import numpy as np
arr2=np.ones((4,5))
print(arr2)
print(arr2.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [22]:
import numpy as np
arr3=np.ones((2,3,3))
print(arr3)
print(arr3.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


In [28]:
import numpy as np
arr3=np.ones((2,3,3),dtype="bool")
print(arr3)
print(arr3.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
3


# create an empty array

In [33]:
import numpy as np
arr=np.empty(3)
print(arr)
print(arr.ndim)

[0. 0. 0.]
1


In [35]:
import numpy as np
arr2=np.empty((3,3))
print(arr2)
print(arr2.ndim)

[[4.67296746e-307 1.69121096e-306 1.33511018e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]
2


# creating an array with a range

In [38]:
import numpy as np
arr=np.arange(1,21)
print(arr)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [40]:
import numpy as np
arr=np.arange(3,101)
print(arr)
print(arr.ndim)

[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100]
1


In [42]:
import numpy as np
arr=np.arange(3,101,3)
print(arr)
print(arr.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
1


In [44]:
import numpy as np
arr=np.arange(5,1001,5)
print(arr)
print(arr.ndim)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

# linspace

In [47]:
import numpy as np
arr=np.linspace(1,10,6)
print(arr)
print(arr.ndim)

[ 1.   2.8  4.6  6.4  8.2 10. ]
1


In [49]:
import numpy as np
arr=np.linspace(1,20,8)
print(arr)
print(arr.ndim)

[ 1.          3.71428571  6.42857143  9.14285714 11.85714286 14.57142857
 17.28571429 20.        ]
1


In [51]:
import numpy as np
arr=np.linspace(5,30,10)
print(arr)
print(arr.ndim)

[ 5.          7.77777778 10.55555556 13.33333333 16.11111111 18.88888889
 21.66666667 24.44444444 27.22222222 30.        ]
1


# shape 

In [54]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [56]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [58]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


# reshape

In [71]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=arr.reshape(2,5)
print(arr)
print()
print(arr1)
print(arr1.ndim)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [73]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr.reshape(3,3)
print(arr)
print()
print(arr1)
print(arr1.ndim)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [83]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
arr1=arr.reshape(3,2,3)
print(arr)
print()
print(arr1)
print(arr1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3


In [93]:
import numpy as np
arr2=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,90]])
arr4=arr2.reshape(1,1,3,4)
print(arr2)
print()
print(arr4)
print()
print(arr4.ndim)


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 90]]

[[[[ 1  2  3  4]
   [ 4  5  6  7]
   [ 7  8  9 90]]]]

4


# ravel and flatten -converts multidimensional to 1D 

In [96]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
one_D=arr3.ravel()
print(arr3)
print(arr3.ndim)
print()
print(one_D)
print(one_D.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

[1 2 3 4 5 6 7 8 9]
1


In [98]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
one_D=arr3.flatten()
print(arr3)
print(arr3.ndim)
print()
print(one_D)
print(one_D.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

[1 2 3 4 5 6 7 8 9]
1


In [108]:
import numpy as np
four_D=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(four_D)
print(four_D.ndim)
one_D=four_D.flatten()
print()
print(one_D)

print(one_D.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4

[1 2 3 4 5 6 7 8 9]
1


# create an array with diagonal elements filled with 1-identity matrix

In [111]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [113]:
import numpy as np
arr=np.eye(3,6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [117]:
import numpy as np
arr=np.eye(5,8)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


# create numpy array with random number
# rand()-the random'module rand() method returns a random float between 0 and 1

In [124]:
import numpy as np
r=np.random.rand(5)
print(r)

[0.30063469 0.19403141 0.35268536 0.59607837 0.54178989]


In [128]:
import numpy as np
r1=np.random.rand(2,3)
print(r1)

[[0.91810282 0.53233738 0.94655759]
 [0.88379694 0.14188461 0.87104149]]


In [130]:
import numpy as np
r2=np.random.rand(2,2,3)
print(r2)

[[[0.94610913 0.32915113 0.82967867]
  [0.1673536  0.61905982 0.32797816]]

 [[0.9627749  0.44425547 0.02461602]
  [0.23097669 0.24998283 0.26825777]]]


# randn()-the function is used to generate a value close to 0 and this may return positive or negative numbers as well

In [143]:
import numpy as np
r=np.random.randn(5)
print(r)
print(r.ndim)
print(r.shape)


[ 0.57100671 -0.06525374 -0.78989042  0.69080833 -1.10553167]
1
(5,)


In [141]:
import numpy as np
r=np.random.randn(2,3)
print(r)
print(r.ndim)
print(r.shape)

[[ 1.80485002 -2.23045599 -2.38393118]
 [-0.31736294 -0.56266878 -0.25461364]]
2
(2, 3)


In [145]:
import numpy as np
r=np.random.randn(2,2,3)
print(r)
print(r.ndim)
print(r.shape)

[[[-0.11335315  0.89214763  0.32375645]
  [ 0.59009111 -0.3051698   0.44313999]]

 [[ 0.23488776 -0.10696135  0.22847262]
  [ 1.53053374 -0.31569783 -0.73739353]]]
3
(2, 2, 3)


# randint

In [148]:
import numpy as np
r=np.random.randint(4,20,5)
print(r)
print(r.ndim)

[ 7 12 10 18  7]
1


In [150]:
import numpy as np
r=np.random.randint(8,101,20)
print(r)
print(r.ndim)

[69 84 51  9 50 11 93 36 88 73 43  8 92 79 49 87 58 11 99 73]
1


# randf
# -this function is used for doing random sampling in numpy.IT returns an array of specified shape and fills it with random floats in the half open interval between 0 and 1

In [159]:
import numpy as np
r=np.random.ranf(5)
print(r)
print(r.ndim)

[0.16120534 0.26176423 0.59432634 0.29077776 0.76834518]
1


In [161]:
import numpy as np
r=np.random.ranf((2,3))
print(r)
print(r.ndim)

[[0.95969671 0.05671986 0.77756195]
 [0.0124289  0.90764603 0.28741049]]
2
