# Matrix

In [5]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(type(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [9]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(type(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


# arithmetic operations in matrix 

In [23]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6]])
arr2=np.matrix([[7,8,9],[10,12,13]])
print(arr1)
print()
print(arr2)
print()
print(arr1+arr2)
print()
print("talking about array")
print()
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,12,13]])
print(arr1)
print()
print(arr2)
print()
print(arr1+arr2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 12 13]]

[[ 8 10 12]
 [14 17 19]]

talking about array

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 12 13]]

[[ 8 10 12]
 [14 17 19]]


In [25]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6]])
arr2=np.matrix([[7,8,9],[10,12,13]])
print(arr1)
print()
print(arr2)
print()
print(arr1-arr2)
print()
print("talking about array")
print()
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,12,13]])
print(arr1)
print()
print(arr2)
print()
print(arr1-arr2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 12 13]]

[[-6 -6 -6]
 [-6 -7 -7]]

talking about array

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 12 13]]

[[-6 -6 -6]
 [-6 -7 -7]]


In [31]:
import numpy as np
print("talking about matrix")
arr1=np.matrix([[1,2],[3,4]])
arr2=np.matrix([[5,6],[7,8]])
print(arr1)
print()
print(arr2)
print()
m=arr1.dot(arr2)
print(m)
print()
print("we are talking about array")
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print()
print(arr2)
print()
print(arr1*arr2)

talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]

we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [35]:
import numpy as np
print("talking about matrix")
arr1=np.matrix([[1,2],[3,4]])
arr2=np.matrix([[5,6],[7,8]])
print(arr1)
print()
print(arr2)
print()
print(arr2/arr1)
print()
print("we are talking about array")
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print()
print(arr2)
print()
print(arr2/arr1)

talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]

we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]


# matrix function
# transpose matrix

In [40]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(np.transpose(arr1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(arr1.T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# swapaxes function

In [47]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(np.swapaxes(arr1,0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [49]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(np.swapaxes(arr1,1,0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# inverse

In [56]:
import numpy as np
arr1=np.matrix([[1,2],[3,4]])
print(arr1)
print()
print(np.linalg.inv(arr1))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# power function

In [63]:
import numpy as np
arr1=np.matrix([[1,2],[3,4]])
print(arr1)
print()
print(np.linalg.matrix_power(arr1,2))
print()
print(np.linalg.matrix_power(arr1,0))
print()
print(np.linalg.matrix_power(arr1,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# determinate

In [69]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(np.linalg.det(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

-9.51619735392994e-16
