# split array

In [15]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(arr1.ndim)
s=np.array_split(arr1,3)
print(s)
print(type(s))
print(s[0])

[1 2 3 4 5 6 7 8 9]
1
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>
[1 2 3]


In [19]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr1)
print()
s=np.array_split(arr1,4,axis=1)
print(s)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [25]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr1)
print()
s=np.array_split(arr1,2,axis=0)
print(s)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Search Array

In [32]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)
print()
x=np.where(arr1==3)
print(x)

[1 2 3 4 5 6 7 8]

(array([2], dtype=int64),)


In [38]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print()
x=np.where(arr1%2==0)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]

(array([1, 3, 5, 7, 9], dtype=int64),)


# searchsorted array

In [43]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.searchsorted(arr1,11)
print(x)

10


In [45]:
import numpy as np
arr1=np.array([10,12,13,14,15,16])
x=np.searchsorted(arr1,11)
print(x)

1


In [47]:
import numpy as np
arr1=np.array([10,12,13,14,15,16])
x=np.searchsorted(arr1,11,side="right")
print(x)

1


In [49]:
import numpy as np
arr1=np.array([10,11,12,16,17,20,23])
x=np.searchsorted(arr1,[13,14,15])
print(x)

[3 3 3]


# sort array

In [54]:
import numpy as np
arr1=np.array([1,55,12,63,20,70,23,5])
x=np.sort(arr1)
print(x)

[ 1  5 12 20 23 55 63 70]


In [56]:
import numpy as np
arr1=np.array(['a','o','p','z','c','d'])
x=np.sort(arr1)
print(x)

['a' 'c' 'd' 'o' 'p' 'z']


In [64]:
import numpy as np
arr1=np.array([[1,2,5],[88,10,96]])
print(arr1)
print()
x=np.sort(arr1)
print(x)

[[ 1  2  5]
 [88 10 96]]

[[ 1  2  5]
 [10 88 96]]


In [70]:
import numpy as np
arr1=np.array([[[10,55,63],[41,63,78]]])
print(arr1)
print()
x=np.sort(arr1)
print(x)

[[[10 55 63]
  [41 63 78]]]

[[[10 55 63]
  [41 63 78]]]


# filter array

In [77]:
import numpy as np
arr1=np.array([12,14,16,57,96,23,44])
f=[True,False,True,False,True,False,True]
b=arr1[f]
print(b)

[12 16 96 44]


# shuffle function

In [85]:
import numpy as np
arr1=np.array([12,13,4,15,100,89,78,63])
print("Before suffle array is",arr1)
np.random.shuffle(arr1)
print("after shuffle array is",arr1)

Before suffle array is [ 12  13   4  15 100  89  78  63]
after shuffle array is [ 15  63  12 100  89  13   4  78]


# unique function

In [96]:
import numpy as np
arr1=np.array([1,5,6,7,8,9,6,66,1,1,2,2,5,5,9,9,10,10])
print(arr1)
x=np.unique(arr1)
print("Unique :",x)

[ 1  5  6  7  8  9  6 66  1  1  2  2  5  5  9  9 10 10]
Unique : [ 1  2  5  6  7  8  9 10 66]


In [94]:
import numpy as np
arr1=np.array([1,5,6,7,8,9,6,66,1,1,2,2,5,5,9,9,10,10])
print(arr1)
x=np.unique(arr1,return_index=True)
print(x)

[ 1  5  6  7  8  9  6 66  1  1  2  2  5  5  9  9 10 10]
(array([ 1,  2,  5,  6,  7,  8,  9, 10, 66]), array([ 0, 10,  1,  2,  3,  4,  5, 16,  7], dtype=int64))


In [102]:
import numpy as np
arr1=np.array([1,5,6,7,8,9,6,66,1,1,2,2,5,5,9,9,10,10])
print(arr1)
x=np.unique(arr1,return_counts=True)
print(x)

[ 1  5  6  7  8  9  6 66  1  1  2  2  5  5  9  9 10 10]
(array([ 1,  2,  5,  6,  7,  8,  9, 10, 66]), array([3, 2, 3, 2, 1, 1, 3, 2, 1], dtype=int64))


In [118]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
x=np.resize(arr1,(3,3))
print(x)
print(x.ndim)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


# insert function

In [123]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.insert(arr1,3,200)
print(x)

[  1   2   3 200   4   5   6   7   8   9  10]


In [127]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.insert(arr1,(3,4),(200,300))
print(x)

[  1   2   3 200   4 300   5   6   7   8   9  10]


# 2D-insert function

In [132]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
x=np.insert(arr1,2,30,axis=1)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2 30  3]
 [ 4  5 30  6]
 [ 7  8 30  9]]


In [134]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
x=np.insert(arr1,2,30,axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [30 30 30]
 [ 7  8  9]]


In [138]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
x=np.insert(arr1,2,[12,12,12],axis=1)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2 12  3]
 [ 4  5 12  6]
 [ 7  8 12  9]]


# append

In [143]:
import numpy as np
arr1=np.array([1,5,6,8,9,10,15,18,56])
print(arr1)
x=np.append(arr1,200)
print(x)

[ 1  5  6  8  9 10 15 18 56]
[  1   5   6   8   9  10  15  18  56 200]


In [149]:
import numpy as np
arr1=np.array([[12,13,14],[15,16,18]])
print(arr1)
print()
x=np.append(arr1,[[100,200,300]])
print(x)

[[12 13 14]
 [15 16 18]]

[ 12  13  14  15  16  18 100 200 300]


# delete function


In [154]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
x=np.delete(arr1,3)
print(x)

[1 2 3 4 5]
[1 2 3 5]


In [160]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
x=np.delete(arr1,0,axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]
